### PR TITLE
Import and Export multiple template library elements using a .zip archive

### PR DESCRIPTION
**Pull request by teolaz**
Hi,
i created the long waited ability to export a .zip archive of selected templates from the template library, and i enabled the import ability for a .zip archive of .json files too, modifying the import_template already done function.
You can see the system in screenshots below:
image
image
image

### CODE REVIEW

**Comment by teolaz** [comment]
@matipojo @joshmarom @arielk @KingYes FYI

**Comment by arielk** [comment]
Thanks for your commit. Looks promising!

We'll check this out after [v1.5](https://github.com/pojome/elementor/milestone/33) release in up coming week.

Thanks

**Comment by arielk** [comment]
@teolaz We want to merge your code, but in the meantime, we have made some changes in the original code. Please merge the master to your branch and re-submit the PR.

Thank you very much for your great work!

**Comment by teolaz** [comment]
@arielk done, please don't change code again, i must rewritten every piece of code with the news you inserted, and i don't want to become stupid for the 3rd time. Thanks :)

**Comment by KingYes** [comment]
Merged by #2056 

Thanks

**Pull request closed without merging**
