### PR TITLE
Ending number of Counter define with shortcode

### PR DESCRIPTION
**Pull request by nathz21**
This modification gives the possibility to define the ending number of the counter widget via a shortcode.
Really helpful if you want to display dynamic statistics (number of members, of posts etc.)

## PR Checklist

- [x] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* Added the possibility to define Counter Ending number via shortcode

## Description

* Change brought to the Counter Widget:
I transformed the Ending number parameter field from Number to Text.
Then I added the do_shortcode() function around the Ending number parameter to give the possibility to define the ending number via a shortcode.

## Test instructions
This PR can be tested by following these steps:

- Create a shortcode that returns a value. Ex: Number of members, of posts, job offers etc.

- Write the shortcode in the Ending number field: [my_shortcode].

- Test the page

## Quality assurance

- [x] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

### CODE REVIEW

**Comment by nathz21** [comment]
Important thing to note: with this modification it is still possible to write a number in the Ending number field.

**Review by DIntriglia — COMMENTED** [review]
Looks interesting, but allowing text in the number field might provide some verifications issues if a non-technical user wants to simply count from 15 - 100. What was your reasoning for the do_shortcode()? What does this feature allow?

**Comment by nathz21** [comment]
Since the text field still allow to type a number I would go for a placeholder : "number or shortcode".

We could also do that for the starting number.

I don't understand your question regarding do_shortcode(), it's the way to activate the possibly used shortcode.

**Comment by DIntriglia** [comment]
Oh, so you are using the do_shortcode similarly to the way dynamic content would work/ACF integration. Will be interesting to see what Elementor’s response is to this as it seems very niche.

**Comment by bainternet** [comment]
@nathz21 

Thanks for the PR but we prefer addressing the core issue here which is to implement dynamic capabilities for number control, please follow #5952

thanks.

**Pull request closed without merging**
