### PR TITLE
Fix warnings in control condtions

### PR DESCRIPTION
**Pull request by crazypsycho**
## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ x ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

* Prevent warnings on nested control conditions

## Description

* If you want to check a dynamicTag is selected, you will get javascript-errors in editor and php-warnings in frontend. This fix will prevent this.

## Test instructions

Add two controls, one with a dynamic tag. If you check the condition in second control, you will get javascript and php warnings, if nothing is selected in the dynamic tag.

Example:
```php

        $element->add_control(
            'myControl',
            [
                'label' => __( 'My DynamicTag', 'myPlugin' ),
                'type' => Controls_Manager::MEDIA,
                'dynamic' => [
                    'active' => true,
                    'categories' => [
                        Module::BASE_GROUP,
                        Module::TEXT_CATEGORY,
                        Module::URL_CATEGORY,
                        Module::GALLERY_CATEGORY,
                        Module::IMAGE_CATEGORY,
                        Module::MEDIA_CATEGORY,
                        Module::POST_META_CATEGORY,
                    ],
                ],
            ]
        );


        $element->add_control(
            'mySecondControl',
            [
                'label' => __( 'Show/Hide' ),
                'type' => Controls_Manager::SELECT,
                'default' => 'hide',
                'options' => [
                    'show' => __( 'Show' ),
                    'hide' => __( 'Hide' ),
                ],
                'conditions' => [
                    'relation' => 'and',
                    'terms' => [
                        [
                            'name' => '__dynamic__',
                            'operator' => '!=',
                            'value' => null,
                        ],
                        [
                            'name' => '__dynamic__[myControl]',
                            'operator' => '!=',
                            'value' => null,
                        ],
                    ],
                ],
            ]
        );
```

It happens also if you check the value of the tag like
```php
'terms' => [
                        [
                            'name' => 'myControl',
                            'operator' => '!=',
                            'value' => null,
                        ],
                        [
                            'name' => 'myControl[url]',
                            'operator' => '!=',
                            'value' => null,
                        ],
                    ],
```

*

## Quality assurance

- [ x ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

### CODE REVIEW

**Comment by Enoray** [comment]
+1

**Comment by bainternet** [comment]
@crazypsycho 

Thanks for the PR, 
Currently, we don't support conditions on things other then values, meaning checking if a value "is dynamic" is not something we see a real need for.

Thanks

**Comment by crazypsycho** [comment]
@bainternet 
You have already a real need for checking if a dynamic field is selected. 
In Group_Control_Background is such a check for image[url].
But there it is working. I will check tomorrow if this bug is already fixed.

**Comment by crazypsycho** [comment]
@bainternet 
I have tested it again. Simple conditions seems to work now:
```
                'condition' => [
                    'dynamicconditions_dynamic!' => '',
                    'dynamicconditions_dynamic[url]!' => '',
                ],
```

But complex conditions still throw errors:
```
'conditions' => [
                    'relation' => 'and',
                    'terms' => [
                        [
                            'name' => 'dynamicconditions_dynamic',
                            'operator' => '!=',
                            'value' => '',
                        ],
                        [
                            'name' => 'dynamicconditions_dynamic[url]',
                            'operator' => '!=',
                            'value' => '',
                        ],
                    ],
                ]
```

I think i can work around this issue.

**Pull request closed without merging**
