### PR TITLE
bulk save templates into library on post/page/cpt backend archive

### PR DESCRIPTION
**Pull request by teolaz**
another feature added, now you have the possibility to bulk save templates into library when on posts/pages/cpts archive edit page

image

### CODE REVIEW

**Comment by teolaz** [comment]
@matipojo @joshmarom @arielk @KingYes FYI

**Comment by teolaz** [comment]
@matipojo @joshmarom @arielk @KingYes checked this? 2 months passed...

**Comment by bainternet** [comment]
@teolaz 

Currently, we feel this should be more of a 3rd party plugin territory.


Thanks for the contributions.

**Comment by teolaz** [comment]
Could i ask exactly why? Just to know when to avoid unwanted pull requests...

**Pull request closed without merging**
