### PR TITLE
Added Fixed Height

### PR DESCRIPTION
**Pull request by DIntriglia**
- Added fixed height to Section, so a forced height could be added instead of just having min-height.

## PR Checklist

- [X] The commit message follows our guidelines:  https://github.com/pojome/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* Added Fixed Height to Sections as a responsive option.

## Description
An explanation of what is done in this PR

* Along with the min-height, there was no way to force an item to be a fixed height. This can resolve the issue in which the element/image you have has a height of 200 px, while you only want to show the top of the image. Min-Height does not allow this, while fixed height does.

## Test instructions
This PR can be tested by following these steps:

* The only file changed is the section.php file. Simply test that file, and it will be good to go. I have been using this change on my own personal installations since 2.06

## Quality assurance

- [X ] I have tested this code to the best of my abilities
- [X ] I have added unittests to verify the code works as intended
- [X ] Docs have been added / updated (for bug fixes / features)

Fixes #

### CODE REVIEW

**Comment by Djimusic** [comment]
This is in reference to PR #4250 

I did not see that you had contacted me regarding that PR until you closed it. This is the PR you have requested.

-Dakotah

**Comment by Djimusic** [comment]
Can we please have an update on this?

**Comment by DIntriglia** [comment]
Should I resubmit this? Any reason this has not been added yet? Such an easy fix, with huge abilities for overlapping elements.

**Comment by DIntriglia** [comment]
@kobizz Any updates? I am more than happy to make changes if need be.

**Comment by lordloadalot** [comment]
In the meantime use css under the css tab of the section ( in addition "overflow: hidden" by now is even a EL-feature )

selector {
height: 200px;
}

**Comment by DIntriglia** [comment]
Thanks for your response @lordlodalot. As of right now, that’s how I’m doing it. The main thing why I did it using this feature is for the responsive nature of Elementor’s toggles, which css does not provide.

**Comment by lordloadalot** [comment]
> Thanks for your response @lordloadalot. As of right now, that’s how I’m doing it. The main thing why I did it using this feature is for the responsive nature of Elementor’s toggles, which css does not provide.

Hi @DIntriglia , with a bit of work you can write your own media queries in CSS.
[https://www.w3schools.com/css/css3_mediaqueries.asp]
They should yet correspond to the breakpoints chosen in ELEMENTOR >> settings >> style
Defaults are :
Tablet: 1025px
Phone:  768px

reference chart breakpoints: [http://stephen.io/mediaqueries/]

**Comment by babakfp** [comment]
@DIntriglia
This is the definition of not giving a f***. They didn't even bother to accept your PR and also we don't have the same freaking option in the new `container` widget😂.
Thank you for your PR dude. I guess don't put your time into this kind of projects next time🌼

**Comment by DIntriglia** [comment]
@babakfp Defiinitely agree. Would have liked to see a response as to why they would not merge in my request. It's also not like it was a feature request. It was a merge request so they just had to review it.

Looking back at it now, Min-Height does usually work and is the better approach, but as a page builder, you should allow all options that are common in CSS and then allow the user to make the mistake as to whether or not use min-height or height.

Would be down to update this PR for the newest version of the code if a person from Elementor would reply and confirm if it will be merged in.

**Comment by arielk** [comment]
Hi @DIntriglia I'm very appropriate your work and effort, but you can see my comment here: https://github.com/elementor/elementor/issues/7129#issuecomment-1224348735

**Pull request closed without merging**
