### PR TITLE
Font register filter

### PR DESCRIPTION
**Pull request by patryk-uszynski**
Hi,

I've added filter, which provides ability to register own font names. There isn't any good way to do this yet, so i think this might be helpful ;) Here - #852 for example.

### CODE REVIEW

**Comment by patryk-uszynski** [comment]
Example usage:
```php
add_action('elementor/fonts_registered', function($fonts) {
	$fonts['My new font'] = 'local';

	return $fonts;
});
```

**Comment by ramiy** [comment]
Nice one!

**Comment by KingYes** [comment]
This code has a memory leak issue. We used `return` the data this way when the function executed all fonts data remove from the memory. In your code it's always keep in the memory inside the new property you created.

**Comment by patryk-uszynski** [comment]
I wanted to avoid multiple `apply_filters` calls. What if I modify that, make property only for new fonts and `return` the data old way with `array_merge`?

**Comment by patryk-uszynski** [comment]
@KingYes any suggestions?

**Comment by KingYes** [comment]
Fixed by #3336

Thanks

**Pull request closed without merging**
