### PR TITLE
New action hooks for attributes

### PR DESCRIPTION
**Pull request by ramiy**
## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* Add new action hook - `elementor/element/before_add_attributes`
* Add new action hook - `elementor/element/{$element_type}/before_add_attributes`
* Add new action hook - `elementor/element/{$element_type}/after_add_attributes`

## Description
An explanation of what is done in this PR

The "**print_element()**" method has 4 action hooks:
* `elementor/frontend/before_render`
* `elementor/frontend/{$element_type}/before_render`
* `elementor/frontend/{$element_type}/after_render`
* `elementor/frontend/after_render`

The "**_add_render_attributes()**" method has only 1 action hook:
* `elementor/element/after_add_attributes`

In this PR I added 3 more action hook:
* `elementor/element/before_add_attributes`
* `elementor/element/{$element_type}/before_add_attributes`
* `elementor/element/{$element_type}/after_add_attributes`

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [x] Docs have been added / updated (for bug fixes / features)

Fixes #

### CODE REVIEW

**Comment by bainternet** [comment]
@ramiy 

Thanks for the PR, Do you have an idea of the performance impact of adding such hooks?

**Comment by ramiy** [comment]
> @ramiy
> 
> Thanks for the PR, Do you have an idea of the performance impact of adding such hooks?

The same performance impact as the current `elementor/element/after_add_attributes` action hook.

**Review by bainternet — APPROVED** [review]

**Comment by KingYes** [comment]
@ramiy Please re-open on `release/2.9.0`.

**Comment by ramiy** [comment]
I can't change branches to closed PRs. Can you reopen it?

**Comment by xclusionmedia** [comment]
Was this ever included? Seems helpful for adding attributes dynamically

**Pull request closed without merging**
