### PR TITLE
New Feature: Element Attributes

### PR DESCRIPTION
**Pull request by ramiy**
Add the ability to define custom "**Attributes**" under the "**Advanced Tab**".

With this new feature you can add your own custom HTML attributes to all your widgets.

You can add any attribute:

* **Global** attribute - `id`, `class`, `style`, `dir`, `title`, `tabindex`, `rel` and others
* **Accessibility** attribute - `role`, `aria-*`
* **JS Data** attribute - `data-*`
* **JS Event** attribute - `onClick`, `onLoad`, `onResize`, `onFocus`, `on*`
* **Schema.org** attribute - `itemscope`, `itemtype`, `itemprop`
* other custom attribute you need

## Attributes Section

A new section added to the advanced tab, with a new repeater where you can define the widget attributes.

element-attributes

## Open Attribute

In each repeater item you can define the attribute key and the attribute value.

element-attributes-open

### CODE REVIEW

**Comment by ramiy** [comment]
Default view when no attributes are added yet:

element-attributes-empty

**Comment by bainternet** [comment]
missing validation for blacklisted attributes like `cid`

**Comment by ramiy** [comment]
@bainternet Do we have a list of those "blacklisted attributes"? or you want me to create a new filterable array?

**Comment by ramonztro** [comment]
Is this planned to be on 2.1.0?

**Comment by KingYes** [comment]
Add blacklist for: `id`, `data-id`, `data-element_type`, `data-model-cid`, `data-settings`.

**Comment by ramiy** [comment]
@ramonztro yes, we plan to add this feature on 2.1.0.

**But**... because of performance issues caused by the repeater control used in each and every widget on the page, we are going to use textarea control.

## No Attributes

elementor-widget-attributes-empty

## With Attributes

elementor-widget-attributes-in-use

**Comment by ramonztro** [comment]
Oh, I see. Well, I guess switching to textarea is not a big deal, at least
for me, but repeater would be better for organisation, though.

Looking forward to use this feature. Nice work!




2018-04-26 11:05 GMT-03:00 Rami Yushuvaev <notifications@github.com>:

**Comment by ramiy** [comment]
elementor-widget-attributes-new

**Comment by Basilakis** [comment]
@ramiy Is that published?

**Comment by bainternet** [comment]
@ramiy @KingYes 

What about nested/inner elements??

**Comment by Stiwano** [comment]
When will it be published? Can't wait for.

**Comment by ideasandpixels** [comment]
Starting a new project where accessibility is everything. Nervous to start using Elementor on it for fear of not being able to satisfy the needs of the client.  Any chance this will be rolling out soon so I can alleviate my fears?

**Comment by parfilov** [comment]
Subscribers asks 10 times a day how can they track Google Analytics and Yandex Metrika targets. I'm really tired to answer the same questions to each.
How Ben, as a digital marketer, could miss this I dont understand ((

**Comment by jezzicaaaaa** [comment]
Do we have an idea of when this will be merged?

**Comment by ideasandpixels** [comment]
@jezzicaaaaa 2.1 is due for release July 4th, if everything goes according to plan. It will come then according to the merge log.

**Comment by ideasandpixels** [comment]
Is this getting merged with Pro 2.1? I built an entire site heavily dependent on accessibility on Elementor when I saw this, thinking it would surely be available by the time I was done. Getting nervous it might not come in this release.

**Comment by ramonztro** [comment]
@ideasandpixels This is tagged as PRO, so I guess it will be released when PRO 2.1 arrives.

**Comment by jezzicaaaaa** [comment]
@ramiy ,  I would just like to know the estimated date of this merge?

**Comment by ideasandpixels** [comment]
Time for the release of the website I've been working on and two months later this has been done, but not released, and I'm facing a lot of trouble with my client. I know that's not your problem, but please, any indication of when this will release would be great.

**Comment by Basilakis** [comment]
@ideasandpixels Can we please do not hear again for the web site you want to release and that this is keeping you?
If you do not want it to be kept, you should have code it your self. It is 10h of work.

**Comment by ideasandpixels** [comment]
I don't think it's a lot to ask for an update on this extremely important feature with implications in marketing, analytics, and accessibility.

**Comment by drawcard** [comment]
Would love an update on this, I'm scratching my head trying to implement Google Analytics Tracking code + Elementor Forms, without somehow relying on attributes settings...

**Comment by ramonztro** [comment]
Why closed? Will it be released or not?

**Comment by ideasandpixels** [comment]
Same question as Ramon. Been watching this for months. Perfect solution for so many issues -- is this being pulled into a release or just dropped?

**Comment by ramonztro** [comment]
@ramiy what happened?

**Comment by ideasandpixels** [comment]
@KingYes I would also like to know what's up. I run into a need for this functionality multiple times on every project I'm doing in Elementor. I keep having to hack stuff together with Javascript hacks instead of just using this already-made solution.

**Comment by Basilakis** [comment]
That feature is never going to go live just so all of u know.

**Comment by ramonztro** [comment]
@Basilakis and why is that?

**Comment by Basilakis** [comment]
Because functionality making more problems that solving them.

**Comment by collizo4sky** [comment]
It's a shame this was closed. Really was looking forward to it.

**Comment by ideasandpixels** [comment]
Well, I guess I have to now. I just thought I'd wait for an official version, which I didn't expect to get dumped for no reason.

**Comment by parfilov** [comment]
To track forms submissions and buttons clicks (I know about [this](https://docs.elementor.com/article/59-button)) with Google Analytics and Yandex Metrika was all what a [needed](https://github.com/pojome/elementor/issues/2685). Why did you climb into the jungle with the attributes, I do not understand?!
Perhaps, I will make a video "why I hate Elementor" and this will be the main reason. I also do not understand how Ben, being a marketer, missed one of the most important moments - the conversions counting.
🤬😡

**Comment by ramiy** [comment]
**UPDATE**: this feature was moved to the **Elementor Pro**, this is why the PR was closed.

**Comment by parfilov** [comment]
Oh, it changes everything!

**Comment by pixelsock** [comment]
@ramiy so is there an updated timeline for this feature? The thread seems outdated as it was promised to be in 2.1

**Comment by ideesimple** [comment]
> **UPDATE**: this feature was moved to **Elementor Pro**, this is why the PR was closed.

Hi Ramiy, i have a Elementor Pro but I don't see where can I add data attribute for the section or other.
can you show me how to proceed?
Best
Laurent

**Comment by drawcard** [comment]
I think what was meant by @ramiy is the the issue has been moved to Elementor Pro (not necessarily resolved or implemented). Elementor Pro's development happens separately to the free GitHub plugin if my understanding is correct.

**Comment by ramiy** [comment]
Hi guys,

I developed this feature because as a user I need this feature too... I have clients that require custom attributes so I'm waiting for this feature too.

But @KingYes close this ticket and moved this feature from **Elementor** to **Elementor Pro**. This decision was made by Elementor's product manager and will not be changed - the free elementor version won't have custom attributes.

The pro version is developed separately in GitLab and it has it's own timeline. Although Pro features are not public domain, I was told by @arielk that this feature will be merged to Elementor Pro 2.3.

For more information talk to  Ariel.

**Comment by arielk** [comment]
I hope it will be merged into one of the upcoming versions of Elemental Pro, probably in v.2.2 or v2.3

Thanks everyone!

**Comment by axeldelat** [comment]
Still following this! how this gets pushed soon!

Cheers

**Comment by szabeee** [comment]
Out in Pro 2.2.0 :)

**Comment by tannerchung** [comment]
It turns out this attribute feature only works to add elements to the wrapper. I'm unable to add attributes directly to the img tag. Does anyone have a work around for this?

**Comment by drawcard** [comment]
For the time being you could set the attribute using JS:
https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_element_setattribute1

**Comment by axeldelat** [comment]
Here's How I fixed it:
Puting a Form ID in the Aditional Options of the form
https://prnt.sc/lpx3ah

That way way I was able to tag the trigger in GTM
https://prnt.sc/lpx3uj

Using this guide:
https://www.optimizesmart.com/event-tracking-in-google-tag-manager-v2-complete-guide/

Hope this helps, I think Elementor People should publish this info.

**Comment by mbgraphicdesign** [comment]
I am also trying to change an attribute within the wrapper. Specifically, on the login widget I would like to change the User field text placeholder to "Username" instead of "Username or Email address" because I am using this page as a private page with no email address login, just a username. I see exactly where to do this within the html code but cannot figure out how to change it within Elementor. Any help is greatly appreciated.

**Comment by tranchausky** [comment]
I has use 
Elementor Version 2.5.16
For function "Edit Image"
How to show "New Feature: Element Attributes"?
https://ibb.co/JjvR2HH

**Comment by drawcard** [comment]
@tranchausky I think it might be a Pro feature only. Are you on a Pro licence?

**Comment by tranchausky** [comment]
> @tranchausky I think it might be a Pro feature only. Are you on a Pro licence?

ok, Thanks, i am use Elementor

**Comment by drawcard** [comment]
You'll need a Pro licence: https://elementor.com/pro

Then you'll get access to the features described here: https://docs.elementor.com/article/445-custom-attributes

**Comment by lelas** [comment]
> It turns out this attribute feature only works to add elements to the wrapper. I'm unable to add attributes directly to the img tag for an image widget. Does anyone have a work around for this?

Yes, most of the time pointless to add attributes to the wrapper. Adding onclick events directly to a button or link (e.g. for tracking link clicks as events in Google Analytics) would be a great improvement to Elementor. It's something Elementor makes harder (doable with GTM or JS, but that's too complex for the average Joe and not ideal in many cases).

Please consider this feature request, Elementor!

**Comment by drawcard** [comment]
For now if you want to add an attribute directly on IMG tags you'll have to use something like Jquery: https://github.com/elementor/elementor/pull/4030#issuecomment-443586860

**Comment by Ephremjlm** [comment]
So I am using Elementor Pro and I have tried everything from the custom HTML widgets, to GTM making tags and triggers for Schema Markup on specific pages. I read through this forum that the attribute tab allows for schema markup to be added, but the "key | value" system is confusing to me. 

I could be wrong but in this instance it looks like we need to use "microdata" from schema.org, as opposed to JSON, but after identifying the schema wouldn't the custom attribute values have to be something like "key | value | value of value"?

Example:
itemscope |
itemtype | http://schema.org/LocalBusiness

itemprop | name | Beachwalk Beachwear & Giftware
itemprop | description | A superb collection of fine gifts and clothing
  to accent your stay in Mexico Beach.

itemprop | address
itemscope |
itemtype | http://schema.org/PostalAddress

itemprop | streetAddress | 3102 Highway 98
itemprop | addressLocality | Mexico Beach
iremprop | addressRegion | FL

(and now how do we go about even breaking that little sub section for address? And I have no clue about how to add multiple addresses from here.)

itemprop | telephone | 999-999-9999


Before anyone goes off I already know that this is super wrong, but I also know that when I write JSON schema its correct because I've validated it. If anyone knows a better add schema to Elementor Pro without it getting blocked, or may can at least tell me that I am dumb and why, I am all ears lol.

**Comment by Ephremjlm** [comment]
Okay so I sometimes had issues with it but for those looking for a direct answer to the how to add schema to elementor question, just use the custom HTML widget, and add your JSON code there.

Like I said, for some reason when I tried it a while ago I was having issues, and I didn't change the code so i'm not quite sure what it was(maybe an update fixed it), but it seems to be working perfectly fine now and google is picking it up no problem.

**Pull request closed without merging**
