### PR TITLE
Tweak: Move box shadow option to normal state and hover state for widget button

### PR DESCRIPTION
**Pull request by rodolphebertozzo**

### CODE REVIEW

**Comment by rodolphebertozzo** [comment]
@avivu ?

**Comment by avivu** [comment]
Hello @rodolphebertozzo,
 Thank you for your work, but we already did those changes internally, and it will be part of the next version.

**Comment by rami-elementor** [comment]
@rodolphebertozzo Please change the branch to `release/3.8.0`.

**Comment by rami-elementor** [comment]
@rodolphebertozzo 

I'm closing this PR as duplicate. See #18249

**Pull request closed without merging**
