### PR TITLE
Image Carousel Filters.

### PR DESCRIPTION
**Pull request by dtbaker**
Two simple filters that will allow theme developers to customize the default Image Carousel slider output.

### CODE REVIEW

**Comment by KingYes** [comment]
In the last version of Elementor you can do that from our global hooks (filters and actions).

Thank you @dtbaker ! :)

**Comment by dtbaker** [comment]
Thanks so much for adding those in!

**Comment by iamntz** [comment]
> In the last version of Elementor you can do that from our global hooks (filters and actions).

@KingYes Can we find somewhere an example or more details on this?

**Comment by KingYes** [comment]
For example filter to change the content:
https://github.com/pojome/elementor/blob/develop/includes/base/widget-base.php#L192

BTW, If you want to register new controls, you can use these hooks:
https://github.com/pojome/elementor/blob/develop/includes/base/element-base.php#L509-L541

We are working on "Skins" system, and when it's will be complete you will know about that :)

Thank you guys

**Comment by iamntz** [comment]
Ah, but these are **old** hooks, hence the confusion :)

Thanks for the explanation.

**Pull request closed without merging**
