### PR TITLE
Enhance Toggle & Accordion widgets with new controls

### PR DESCRIPTION
**Pull request by ramiy**
Related: #2599 and #2431

This PR allows the user to change the **Icon Position** and **Icon Color** in the Toggle & Accordion widgets.

elementor-at

NOTE: the Accordion widget already has a position control. This PR adds the same control to the Toggle widgets. As for color control, it's a new control in both widgets.

### CODE REVIEW

**Comment by ramiy** [comment]
@KingYes Don't merge yet. I need to add two controls to select an **Icon** and an **Active Icon**.

**Comment by ramiy** [comment]
New Icon settings:

icon-settings

**Comment by ramiy** [comment]
Last version

icon-settings

**Comment by ramiy** [comment]
New "**Padding**" controls added to **Accordion** and **Toggle** widgets.

new

**Comment by ramiy** [comment]
New "**Title HTML Tag**" control added to **Accordion** and **Toggle** widgets.


title-html-tag

**Comment by arielk** [comment]
1. Toggle & Accordion: Add CSS reset margin/padding for all Headings (theme compatibility)
2. Accordion: If you remove the icons, the active icon its still there 
3. Toggle: Icon/active is not not working at all in the editor 
4. Toggle & Accordion: Remove `span` and `p` from the Title HTML Tag control - It’s not block properties

**Comment by ramiy** [comment]
Updated panels:

### Content
e-c

### Style
e-s

**Pull request merged**
