### PR TITLE
If Image Carousel caption is set to none, don't print the markup for the figcaption

### PR DESCRIPTION
**Pull request by carasmo**
If Image Carousel caption is set to none, don't print the markup for the figcaption

### CODE REVIEW

**Comment by KingYes** [comment]
Thanks!

**Comment by carasmo** [comment]
You're welcome. I see that I made a spelling error. I wrote `carosel_caption` in 3 locations -- it should be `carousel_caption`. Will this be a pain to fix?

**Comment by KingYes** [comment]
You can see my commit about this too :)

**Comment by carasmo** [comment]
Much better! Thanks!

**Pull request merged**
