### PR TITLE
Fix: The "What s New" string in the Editor is not translatable [ED-14985]

### PR DESCRIPTION
**Pull request by DAnn2012**
## PR Checklist

- [x] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* [i18n] The string "What's New" in Editor Notifications is not displayed translated

## Description
An explanation of what is done in this PR

* Fix for the string "What's New" in Editor Notifications is not displayed translated

## Test instructions
This PR can be tested by following these steps:

* Before - Editor v1 (Language set to Spanish)
whats-new-v1-1

* After - Editor v1 (Language set to Spanish)
whats-new-v1-2

* Before - Editor v2 (Language set to Spanish)
whats-new-v2-1

* After - Editor v2 (Language set to Spanish)
whats-new-v2-2

## Quality assurance

- [x] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

### CODE REVIEW

**Comment by DAnn2012** [comment]
Hi @KingYes  ,

please could you kindly take a look at my PR?

Thank you.

**Comment by DAnn2012** [comment]
Hi @louiswol94 ,

please could you kindly take a look at my PR?

Thank you.

**Comment by DAnn2012** [comment]
Hi @KingYes ,

please could you kindly take a look at my PR?

Thank you.

**Comment by DAnn2012** [comment]
Hi @louiswol94 ,

please could you kindly take a look at my PR?

Thank you.

**Comment by DAnn2012** [comment]
Hi @TzviRabinovitch ,

please could you kindly take a look at my PR?

Thank you.

**Comment by DAnn2012** [comment]
Hi @louiswol94 ,

please could you kindly take a look at my PR?

Thank you.

**Comment by DAnn2012** [comment]
Hi @hein-obox  ,

please could you kindly take a look at my PR?

Thank you.

**Review by rami-elementor — APPROVED** [review]

**Pull request merged**
