### PR TITLE
Tweak: Add a responsive alignment and spacing options to Image caption for some widgets

### PR DESCRIPTION
**Pull request by rodolphebertozzo**
- Tweak: Add a responsive alignment option to Image caption to image widget
- Tweak: Add a spacing between image and caption to image widget
- Tweak: Add a responsive alignment option to Image caption to image carousel widget
- Tweak: Add a spacing between image and caption to image carousel widget
- Tweak: Add a responsive alignment option to Image caption to basic gallery widget
- Tweak: Add a spacing between image and caption to basic gallery widget
jet2
jet

### CODE REVIEW

**Comment by rodolphebertozzo** [comment]
@rami-elementor

**Comment by rodolphebertozzo** [comment]
@matipojo

**Comment by rodolphebertozzo** [comment]
@StyleShit

**Comment by rodolphebertozzo** [comment]
@matipojo

**Comment by rami-elementor** [comment]
If the PR tests are failed, it won't be merged.

**Pull request closed without merging**
