### PR TITLE
Added is_anchor switch for heading

### PR DESCRIPTION
**Pull request by iamntz**
Sometimes I need to add anchors to some headings, but adding anchor elements sometimes may be an overkill.

### CODE REVIEW

**Comment by arielk** [comment]
We plan to add an option ID to any element in Elementor. You can follow it on this issue: #939 

Thanks for your PR!

**Comment by iamntz** [comment]
Right, but this feature purpose would be to have a simple, predictible way of adding a html anchor for titles. Not for styling (which you would made for the _container_) but solely for anchoring.

**Comment by arielk** [comment]
You can use bay Menu Anchor widget for this..

**Comment by iamntz** [comment]
I know, but say you want to have a title like `My Awesome Title` anchored. You will manually add a menu anchor called `my-awesome-title`. Then if you want to change the title to `Puppies and feathers`, you'll also need to change the anchor, to match the title, othewise will not be too semantically. :)

In case you wonder about the usecase: I'm having some kind of documentation on a page, with various sections.

**Comment by arielk** [comment]
It's a good idea but it's problematic. because it works well only with titles in English, but if you write with different languages (like: Hebrew, Arabic..) it doesn't work because the letters are different.

**Comment by iamntz** [comment]
Hmmm, you're right. Maybe those users should fallback on menu anchor field?

**Comment by arielk** [comment]
So I think the best option right now is to use the Anchor widget.

**Comment by pingram3541** [comment]
My issue is scrollTop always scrolls past the anchor no matter what I try to do for vertical margin/padding on that anchor because it is an inline element (without custom css) so I have to remember to adjust that on the containing element which is often a trial and error process of testing a dozen page loads until I get it just right for all views.

Still don't understand what's so taboo about adding ID attributes to sections and columns when they are indeed a useful part of html spec and are likely not going to break anything as most browsers ignore that "there can only be one!" anyway.

**Comment by iamntz** [comment]
@pingram3541 you can do like i did: fork the project, merge your changes, create PRs. Either the PR are accepted or not, you're able to do your job. The only downside is that you need to `git pull` every now and then to bee up to date.

Most needed changes are a matter of 1-2 lines of code, so there are very small chances of conflicts.

**Comment by pingram3541** [comment]
Great suggestion.  I'll get cracking =)

**Pull request closed without merging**
