### PR TITLE
Add filter to document container attributes

### PR DESCRIPTION
**Pull request by maryisdead**
Adds a filter "elementor/document/container_attributes" to ElementorPro\Modules\ThemeBuilder\Documents\Single_Post::get_container_attributes().

## PR Checklist

- [x] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

See description at top of PR.

## Description
An explanation of what is done in this PR

See description at top of PR.

## Test instructions
This PR can be tested by following these steps:

By adding a filter and checking the output for the attributes applied, eg.:

```
add_filter( 'elementor/document/container_attributes', function ($attributes, $document ) {

    if ($document instanceof ElementorPro\Modules\ThemeBuilder\Documents\Single_Post) {
        $attributes['data-clarity-region'] = 'article';
    }

    return $attributes;

}, 10, 2 );
```

## Quality assurance

- [x] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [x] Docs have been added / updated (for bug fixes / features)

Fixes #

### CODE REVIEW

**Comment by udidol** [comment]
Hi @maryisdead, 
thank you for your contribution.
To contribute to Elementor, you must sign our CLA agreement.
See the notification from the "CLA Assistant".
image

**Review by codewithabdulrahman — APPROVED** [review]

**Comment by maryisdead** [comment]
I can't sign your CLA. That thing seems to be broken.

This is all I get there:
image

**Comment by udidol** [comment]
Will check

**Comment by maryisdead** [comment]
CLA signing worked now.

**Comment by udidol** [comment]
@maryisdead
We generally use feature, development, and versioned branches for releases.
Please check out the branch `elementor:develop`, perform your filter addition on that branch, then PR from your fork's `develop` branch into `elementor:develop`, then we will be able to incorporate it in an upcoming release.

**Pull request closed without merging**
