### PR TITLE
Fix: Internal - Swiper Util accepts only jQuery instances as the container parameter [ED-6050]

### PR DESCRIPTION
**Pull request by guyc-E**

### CODE REVIEW

**Review by udidol — APPROVED** [review]

**Comment by mateustav** [comment]
@guyc-E @yossi-elementor do you know when this is getting deployed? 🙏

**Comment by udidol** [comment]
@mateustav in the upcoming patch version, very soon.

**Comment by stefanullinger** [comment]
Fuck, the release of v3.11 broke all my sliders because of this issue.

**Comment by udidol** [comment]
@stefanullinger It wasn't this PR that broke it, but I did find the issue.
Do you use a custom slider or one of Elementor's widgets?

**Comment by stefanullinger** [comment]
@udidol I mean that it has not been fixed in Elementor v3.11. and thus Elementor v3.11 will require me to pass it as a jQuery element, but I was using a DOM element everywhere. I have a custom slider that I initilize like this.

```
(function($) {
	"use strict";

	var elementSelector = ".sc-teamSlider";

	if (window.jQuery) {
		jQuery(window).on('elementor/frontend/init', function() {
			elementorFrontend.hooks.addAction( 'frontend/element_ready/sc-team-slider.default', function($element) {
				initElement($element.find(elementSelector).get(0));
			} );
		});
	}

	function initElement(element) {
		var $element = $(element);

		var swiperElement = $element.find('.swiper-container').get(0);
		var swiperConfig = {
			...
		};

		if ( 'undefined' === typeof Swiper ) {
			const asyncSwiper = elementorFrontend.utils.swiper;
		
			new asyncSwiper( swiperElement, swiperConfig );
		} else {
			new Swiper( swiperElement, swiperConfig );
		}
	}
})(jQuery);
```

**Comment by udidol** [comment]
I see. We will include a fix for thisin the upcoming patch version.

**Pull request merged**
