### PR TITLE
Add excerpt field to Elementor page settings

### PR DESCRIPTION
**Pull request by ramiy**
Related: #1579 (Enhancing the "Page Setting" panel)

page-settings-excerpt

### CODE REVIEW

**Comment by arielk** [comment]
Thanks @ramiy 

But you need to check if the current CPT is support `excerpt` parameter

**Comment by ramiy** [comment]
@arielk Done.

Tested on **Pages** that don't support excerpts. And then add excerpt support with [Page Excerpt Plugin](https://wordpress.org/plugins/page-excerpt/).

**Comment by ramiy** [comment]
The PR hides the `excerpt` field when the post type has no excerpt support. But I think that it would be better to display the excerpt field and mark it with `disabled` attribute (see #1571).

**Comment by KingYes** [comment]
@arielk Nice catch!

Thanks @ramiy

**Pull request merged**
