### PR TITLE
Tweak: Added "em" unit for some widgets for border radius [ED-6775]

### PR DESCRIPTION
**Pull request by rodolphebertozzo**
- Tweak: Added `em` unit to the border radius of the image widget (props @rodolphebertozzo)
- Tweak: Added `em` unit to the border radius of the icon widget (props @rodolphebertozzo)
- Tweak: Added `em` unit to the border radius of the image box widget (props @rodolphebertozzo)
- Tweak: Added `em` unit to the border radius of the icon box widget (props @rodolphebertozzo)
- Tweak: Added `em` unit to the border radius of the image carousel widget (props @rodolphebertozzo)
- Tweak: Added `em` unit to the border radius of the social icons widget (props @rodolphebertozzo)
- Tweak: Added `em` unit to the border radius of the image gallery widget (props @rodolphebertozzo)
- Tweak: Added `em` unit to the border radius of the progress widget (props @rodolphebertozzo)
- Tweak: Added `em` unit to the border radius of the testimonial widget (props @rodolphebertozzo)

### CODE REVIEW

**Comment by rodolphebertozzo** [comment]
@matipojo

**Review by udidol — DISMISSED** [review]

**Comment by rodolphebertozzo** [comment]
@yossi-elementor

**Comment by rodolphebertozzo** [comment]
@rami-elementor, done.

**Review by rami-elementor — DISMISSED** [review]

**Comment by rami-elementor** [comment]
> @rami-elementor, do you still plan to include it in version 3.6, or shall I move it to version 3.7?

Please move it to 3.7.

**Comment by rami-elementor** [comment]
> @rami-elementor, do you still plan to include it in version 3.6, or shall I move it to version 3.7?

Please move it to 3.7.

**Comment by rodolphebertozzo** [comment]
@rami-elementor, can you merge release/3.7 into PR

**Comment by rodolphebertozzo** [comment]
@rami-elementor. Done!

**Review by matipojo — APPROVED** [review]

**Comment by matipojo** [comment]
Thanks, @rodolphebertozzo!

**Pull request merged**
