### PR TITLE
Tweak: Added text stroke for some widgets [ED-6794]

### PR DESCRIPTION
**Pull request by rodolphebertozzo**
- Tweak: Added text stroke to number for counter widget
- Tweak: Added text stroke to title for counter widget
- Tweak: Added text stroke to text for divider widget
- Tweak: Added text stroke to title for image box widget

### CODE REVIEW

**Comment by rami-elementor** [comment]
Thank you for the PR, but it seems like we are already working on a similar patch. I will send your PR to the relevant developer who is working on this.

**Comment by rodolphebertozzo** [comment]
Thanks @rami-elementor for your answer, it will help the developer to skip this step ;), I haven't seen a PR on this in months, so I opened it, it saves time.

**Comment by avivu** [comment]
Hello @rodolphebertozzo 

Thank you for your suggestions.
I want to move this PR for a review (ED-6794), but I would like to make some changes.

At this point, we will not continue implementing the following suggestions:
- Tweak: Added text shadow to text for divider widget
- Tweak: Added text stroke to description for image box widget
- Tweak: Added text stroke to content for testimonial widget
- Tweak: Added text stroke to name for testimonial widget
- Tweak: Added text stroke to job for testimonial widget
- Tweak: Added text stroke to text for button widget

Please adjust your code and PR description.
Thank you!

**Comment by rodolphebertozzo** [comment]
Hi @avivu, I just applied the requested changes, and updated the PR description. Thanks for your answer!

**Comment by avivu** [comment]
Hi @rodolphebertozzo 

Thank you!
Two last changes:
1. Please add the text stroke also to the title of the Icon Box widget (so it will match the Image box)
2. Remove the "text shadow" from the PR title and update the PR description with the new Icon Box addition.

**Review by rami-elementor — APPROVED** [review]

**Comment by rodolphebertozzo** [comment]
Hi @avivu, it already appears

**Comment by avivu** [comment]
You know better than me :) Thank you @rodolphebertozzo

**Comment by rodolphebertozzo** [comment]
@rami-elementor, ready for merge

**Comment by rami-elementor** [comment]
@rodolphebertozzo I was told your code was approved. It will be merged.

**Comment by rodolphebertozzo** [comment]
Hi, I renamed the branch, so that the current one was deleted, this PR was replaced by this one: https://github.com/elementor/elementor/pull/18533. The code remains exactly the same.

**Pull request closed without merging**
