### PR TITLE
Tweak: Optimize elementor control stack performance

### LINKED ISSUE #13099: ✅ 🐞 Slow server response caused by Elementor's poor performance on complex pages
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

**Problem**

Elementor Pro user here. The server response time of my site is about 30 times slower when Elementor is enabled.

**Case**

> Testing in _localhost_ to prevent any noise caused by the connection speed.

Loading the same page:

- No plugins enabled: ~300 milliseconds for server to respond.
- Elementor & Elementor Pro plugins enabled: ~7 seconds for server to respond.

image

For simplicity I've only included two requests in the screenshot, however:

- the results are consistent over time;
- not affected by the order in which I make the requests (first with plugins disabled then enabled or viceversa);
- there are no other plugins installed;
- no caches of any kind enabled.;

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.38 (Debian)
	MySQL version: MySQL Community Server - GPL v8.0.22
	PHP Version: 7.4.11
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
		 - Elementor uploads directory
		 - .htaccess file
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.3
	Site URL: http://127.0.0.1
	Home URL: http://127.0.0.1
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 2048M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor Child
	Version: 2.3.0.282
	Author: Jesus Iniesta
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.0.13
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.6
		Author: Elementor.com


== Must-Use Plugins ==
	LearnDash LMS Multisite
		Version: 1.0.0
		Author: LearnDash

	Plugin Organizer MU
		Version: 10.1.4
		Author: Jeff Sterup


== Elements Usage ==
	
	archive : 3
		archive-posts : 2
		heading : 3
		posts : 1
		theme-archive-title : 3
	custom_grid : 0
		ele-loop-item : 3
	footer : 2
		form : 2
		heading : 2
		icon-list : 6
		social-icons : 2
		text-editor : 4
	header : 1
		heading : 2
		nav-menu : 6
		theme-site-logo : 3
	loop : 0
		animated-headline : 1
		button : 1
		call-to-action : 2
		divider : 2
		flip-box : 1
		heading : 13
		image : 3
		image-box : 2
		progress : 1
		spacer : 9
		text-editor : 20
		tpc_loop_widget : 1
	page : 83
		alert : 2
		animated-headline : 3
		author-box : 3
		bdt-accordion : 38
		blockquote : 3
		button : 42
		divider : 79
		eael-advanced-data-table : 2
		eael-cta-box : 2
		eael-progress-bar : 18
		form : 9
		heading : 227
		html : 5
		icon : 1
		icon-box : 11
		icon-list : 29
		image : 126
		image-box : 4
		ld-course-content : 1
		ld-courses : 1
		login : 1
		menu-anchor : 6
		nav-menu : 1
		post-comments : 4
		post-info : 2
		posts : 4
		share-buttons : 2
		social-icons : 2
		spacer : 96
		text-editor : 224
		theme-post-featured-image : 1
		theme-post-title : 2
		theme-site-logo : 2
		tpc_loop_widget : 5
		tpc_user_loop_languages_widget : 1
		tpc_user_loop_social_media_icons : 2
		video : 4
	popup : 9
		form : 3
		global : 1
		heading : 4
		html : 1
		spacer : 2
		template : 1
		text-editor : 3
		wp-widget-logy_login_widget : 1
		wp-widget-logy_register_widget : 1
	section : 15
		animated-headline : 1
		button : 8
		divider : 2
		eael-progress-bar : 1
		global : 3
		heading : 14
		html : 1
		icon-box : 1
		image : 4
		image-box : 1
		login : 1
		social-icons : 1
		spacer : 3
		text-editor : 7
		tpc_loop_widget : 3
		tpc_user_loop_social_media_icons : 1
		wp-widget-mepr_login_widget : 1
	single : 2
		author-box : 2
		button : 2
		divider : 2
		global : 1
		heading : 3
		post-comments : 2
		post-info : 1
		post-navigation : 1
		posts : 1
		share-buttons : 1
		spacer : 9
		text-editor : 1
		theme-post-content : 2
		theme-post-featured-image : 1
		theme-post-title : 2
		wp-widget-dwqa-related-question : 1
	widget : 0
		author-box : 27
		blockquote : 3
		button : 3
		divider : 3
		eael-contact-form-7 : 1
		eael-cta-box : 15
		eael-progress-bar : 2
		form : 199
		heading : 24
		image : 15
		text-editor : 4
	wp-post : 15
		author-box : 1
		blockquote : 2
		button : 2
		divider : 3
		eael-advanced-data-table : 1
		eael-cta-box : 1
		eael-progress-bar : 6
		elementskit-tab : 1
		form : 1
		global : 2
		heading : 15
		html : 1
		icon : 1
		image : -1
		ld-course-content : 1
		post-info : 1
		posts : 1
		share-buttons : 1
		spacer : 7
		text-editor : 31
		theme-post-featured-image : 2
		theme-post-title : 2
	wp-page : 17
		alert : 1
		animated-headline : 1
		author-box : 1
		bdt-accordion : -14
		button : -1
		divider : -7
		form : 0
		heading : -100
		html : 3
		icon-box : 4
		icon-list : -39
		image : -36
		image-box : -8
		menu-anchor : 3
		post-comments : 1
		post-info : 1
		posts : 1
		spacer : -113
		text-editor : -87
		video : 1
		wp-widget-logy_login_widget : 1
		wp-widget-logy_register_widget : 2
		wp-widget-mepr_login_widget : 1
	single-page : 5
		alert : 1
		bbp-activity : 1
		bbp-profile-completion : 1
		button : 6
		divider : 6
		eael-event-calendar : 1
		heading : 23
		icon-list : 7
		image : 11
		ld-courses : 1
		menu-anchor : 3
		posts : 1
		shortcode : 1
		spacer : 9
		text-editor : 4
		theme-post-content : 1
		wp-widget-bp_core_members_widget : 1
		wp-widget-bp_xprofile_profile_completion_widget : 1
	bpb-buddypress : 0
		bpb-groups-directory-filters : 1
		bpb-groups-directory-item-actions : 1
		bpb-groups-directory-item-avatar : 1
		bpb-groups-directory-item-cover-image : 1
		bpb-groups-directory-item-description : 1
		bpb-groups-directory-item-last-activity : 1
		bpb-groups-directory-item-meta : 1
		bpb-groups-directory-item-name : 1
		bpb-groups-directory-list : 1
		bpb-groups-directory-navigation : 1
		bpb-members-directory-filters : 1
		bpb-members-directory-item-actions : 1
		bpb-members-directory-item-avatar : 1
		bpb-members-directory-item-last-activity : 1
		bpb-members-directory-item-last-online : 1
		bpb-members-directory-item-name : 1
		bpb-members-directory-list : 1
		bpb-members-directory-navigation : 1
		bpb-profile-group-avatar : 1
		bpb-profile-group-buttons : 1
		bpb-profile-group-content : 1
		bpb-profile-group-description : 1
		bpb-profile-group-last-activity : 1
		bpb-profile-group-leadership : 1
		bpb-profile-group-name : 1
		bpb-profile-group-navigation : 1
		bpb-profile-group-status : 1
		bpb-profile-member-avatar : 2
		bpb-profile-member-buttons : 2
		bpb-profile-member-content : 2
		bpb-profile-member-cover : 1
		bpb-profile-member-last-activity : 2
		bpb-profile-member-meta : 2
		bpb-profile-member-navigation : 2
		bpb-profile-member-username : 2
		bpb-sitewide-content : 1
		bpb-sitewide-filters : 1
		bpb-sitewide-form : 1
		bpb-sitewide-item-avatar : 1
		bpb-sitewide-item-buttons : 1
		bpb-sitewide-item-comments : 1
		bpb-sitewide-item-content : 1
		bpb-sitewide-item-meta : 1
		button : 1
		heading : 5
		text-editor : 5


== Log ==
	

				
```
</details>

### PR DESCRIPTION
**Pull request by deeprobin**
**:warning: This PR is a draft - Not everything has been tested yet**

## PR Checklist
- [x] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?
- [x] Refactoring (no functional changes, no api changes)

## Summary

This PR can be summarized in the following changelog entry:

* Optimize performance of diverse control stack functions (TTFB optimization)

## Description
An explanation of what is done in this PR

* Replace preg_match / Regex-Methods with custom parsing logic

## Test instructions
This PR can be tested by following these steps:

* Automatic Tests
  * Run PHPUnit `composer test`
* Manual Tests
  * Start WordPress instance with installed Elementor & e.g. Elementor Hello Theme
  * (optional / for performance verification): Install Code Profiler Pro (paid) plugin for performance tracing
  * (alternative): Use Xdebug
  * 1. Check functionality: Does also a complex page render?
  * 2. Are there regressions in performance & functionality?

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #13099

### CODE REVIEW

**Comment by KingYes** [comment]
Hi @deeprobin
I really want to check your code but unfortunately, I can't get it to work on my env. Did you check it out?

**Comment by KingYes** [comment]
Ok, I fixed the key index.
Can you share how you make sure this code runs faster?

**Comment by deeprobin** [comment]
Hi @KingYes,

thank you so much for discovering the PR so quickly.

I personally have made the experience that in the PHP environment the regex could mostly always be accelerated by a manual parse method (except in a few edge cases).

I haven't done any benchmarks here yet, as I haven't been able to test my own change yet either.

Therefore the whole thing is still a draft PR.

I would definitely take a closer look at this during the week & then also provide benchmarks or something measurable that this is an improvement & not a regression.

---

The issue I have so far, which is why I haven't been able to test yet was that I haven't found proper onboarding documentation since this is my first PR in the Elementor repo.

My last issue was that Elementor targets a lower PHP version than I have installed. 
The docker-compose file seems to only cover the PHPUnit tests.

How do you guys at Elementor test your changes? Do you manually copy them into the plugins folder of the WordPress instance.

I've mostly worked with a WordPress instance in Docker so far.

**Comment by bainternet** [comment]
Hi @deeprobin,

We did some internal tests and we are really seeing and performance gain, not on page load speed or memory consumption.

In theory you are co

**Comment by deeprobin** [comment]
Hi @baintheinternet,

Unfortunately, I haven't been able to continue working here for a week now.

I haven't been able to test the whole thing yet. Maybe that's because I'm primarily working on PHP 8 and Elementor is probably still using something older here.

I found out that I probably have to work with wp-env and that docker-compose is only for unit & integration tests.

Is there a little documentation somewhere on how to set up Elementor in my development environment?

How do you do your performance tests internally? What is the way you do it as Elementor team? XDebug? Or plugins like Code Profiler Pro?

This attached issue seems to be fatal in terms of performance, which is why I really want to improve something here.

**Comment by deeprobin** [comment]
Closing this - upstream changes are already improving performance.

**Pull request closed without merging**
