### PR TITLE
Fix: [i18n] Some strings in Admin Feedback and Announcements are not displayed translated

### PR DESCRIPTION
**Pull request by DAnn2012**
## PR Checklist

- [x] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* [i18n] Some strings in Admin Feedback, Kit Elements Defaults and Announcements are not displayed translated

## Description
An explanation of what is done in this PR

* Fix for some strings in Admin Feedback, Kit Elements Defaults and Announcements are not displayed translated if the language is not English

## Test instructions
This PR can be tested by following these steps:

* Before (Language set to Italian)
admin-feedback-before

announcement-before

save-as-before

* After (Language set to Italian)
admin-feedback-after

announcement-after

save-as-after

## Quality assurance

- [x] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

### CODE REVIEW

**Comment by DAnn2012** [comment]
Hi @rami-elementor ,

please could you kindly take a look at my PR?

Thank you.

**Comment by DAnn2012** [comment]
Hi @hein-obox ,

please could you kindly take a look at my PR?

Thank you.

**Comment by DAnn2012** [comment]
Hi @KingYes 

please could you kindly take a look at my PR?

Thank you.

**Comment by DAnn2012** [comment]
Hi @louiswol94 

please could you kindly take a look at my PR?

Thank you.

**Review by rami-elementor — DISMISSED** [review]

**Comment by DAnn2012** [comment]
Hello @louiswol94 and @TzviRabinovitch 

When will this PR of mine be added to the merge queue?

Thanks.

**Comment by ramiy** [comment]
Related: #23076 #23139

**Review by bainternet — DISMISSED** [review]
looks good, just like previous ones ex: #23076

**Review by KingYes — APPROVED** [review]

**Pull request merged**
