### PR TITLE
Fix: [i18n] Some strings in admin-apps-page.php are not displayed translated - 3.21

### PR DESCRIPTION
**Pull request by DAnn2012**

### CODE REVIEW

**Comment by DAnn2012** [comment]
Hi @louiswol94 ,

please could you kindly take a look at my PR this time for version 3.21?

Thank you.

**Comment by DAnn2012** [comment]
Hi @louiswol94 ,

please could you kindly take a look at my PR?

Thank you.

**Comment by DAnn2012** [comment]
Hi @KingYes ,

please could you kindly take a look at my PR?

Thank you.

**Comment by DAnn2012** [comment]
Hi @netanelavr  ,

please could you kindly take a look at my PR this time for version 3.21?

Thank you.

**Comment by DAnn2012** [comment]
Hi @louiswol94 ,

please could you kindly take a look at my PR this time for version 3.21?

Thank you.

**Review by rami-elementor — DISMISSED** [review]

**Comment by rami-elementor** [comment]
@DAnn2012 any chance you can close this PR and create the same PR on both `main` and `3.22` branches?

**Comment by DAnn2012** [comment]
Hello @rami-elementor 

I've done this already: #25497 for `main` and https://github.com/elementor/elementor/blob/3.22/modules/apps/admin-apps-page.php for `3.22` branches.

So should I close this PR for `3.21`?

**Comment by rami-elementor** [comment]
Closing 3.21 PR. Thank you for your contribution.

**Pull request closed without merging**
