### PR TITLE
Added Fixed Height for section option.

### PR DESCRIPTION
**Pull request by DIntriglia**
I edited the code to add Fixed Height as an option for Elementor. I needed this for my own project, and was trying to do it via CSS, but I wanted to use the responsive options that elementor is great at. Very light weight change.

### CODE REVIEW

**Comment by Djimusic** [comment]
I have updated this Merge Request to include the request from #4251. Please look over my changes and provide suggestions if implementation would like to be implemented a different way.

**Comment by Djimusic** [comment]
Looks like the CI failed due to a composer error, not my plugin code.

**Comment by Djimusic** [comment]
Any update on this?

**Comment by Djimusic** [comment]
@KingYes Wanted to check on this? I am still compiling my version every time there is an update, and would love to have this built in.

**Comment by bainternet** [comment]
@Djimusic 
Can you create a new PR with just the fixed height?

**Pull request closed without merging**
