### PR TITLE
Fix: Corrections in two files of modules/promotions/admin-menu-items/ for localization - 3.21

### PR DESCRIPTION
**Pull request by DAnn2012**

### CODE REVIEW

**Comment by DAnn2012** [comment]
Hi @louiswol94 ,

please could you kindly take a look at my PR?

Thank you.

**Comment by DAnn2012** [comment]
Hi @KingYes ,

please could you kindly take a look at my PR?

Thank you.

**Comment by DAnn2012** [comment]
Hi @netanelavr  ,

please could you kindly take a look at my PR this time for version 3.21?

Thank you.

**Comment by rami-elementor** [comment]
@DAnn2012 Nice catch! Please close this PR, and open the same changes on the `main` and `3.22` branches.

**Comment by DAnn2012** [comment]
Hello @rami-elementor

I've done this already: #25498 for `main` and https://github.com/elementor/elementor/blob/3.22/modules/promotions/admin-menu-items/custom-icons-promotion-item.php#L25 and https://github.com/elementor/elementor/blob/3.22/modules/promotions/admin-menu-items/form-submissions-promotion-item.php#L25 for `3.22` branches.

So should I close this PR for `3.21`?

**Comment by rami-elementor** [comment]
Thank you, I'm closing this PR for 3.21.

**Pull request closed without merging**
