### PR TITLE
Fix Pro URL in contact-buttons-render-base

### PR DESCRIPTION
**Pull request by szepeviktor**
## PR Checklist
- [x] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] Other... Please describe: fix an URL

## Summary

Without the trailing slash it produces a redirect.

### CODE REVIEW

**Comment by szepeviktor** [comment]
@elementorbot stop

**Comment by toineenzo** [comment]
> @elementorbot stop

Why are you arguing with a bot lol

**Comment by szepeviktor** [comment]
@toineenzo Friendly ping 🏓

**Comment by szepeviktor** [comment]
Oh no! `conversion-center` is gone.

**Pull request closed without merging**
