### PR TITLE
Tweak: Make the Container element extendable [ED-12042]

### PR DESCRIPTION
**Pull request by HadyShaltout**
## PR Checklist

- [x] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary
Modify the access modifiers from '`private`' to '`protected`' to allow the extension of [`before_render, after_render`] functions in third-party plugins

## Description

Like my PR https://github.com/elementor/elementor/pull/13618 to extend section element, Now the container element is not extendable, So we need to give the developers the ability to customize the container as they wish, It will be useful for adding Canvas backgrounds or any custom background instead of default Images and Videos.

## Test instructions
Developers can Extends the `\Elementor\Includes\Elements\Container` class and override the functions [`content_template`], [`before_render`], [`after_render`]

**Full Example to Extend the New Container Class**

```
namespace ExtendElementor;

class ContainerNew_Override extends \Elementor\Includes\Elements\Container {
    
    private $section_id = '';

    /**
     * Constructor of Element_Base
     * 
     * @param array $data 
     * @param array $args 
     */
    public function __construct( $data = array(), $args = null ) {
        
        parent::__construct( $data, $args );
        
        $this->section_id = $this->get_id();

        /* Canvas Libraries - Three */
        wp_register_script( ( __MAIN_PREFIX . '-js-main' ), CUSTOM_FUNCTION_GET_ABSOLUTE_PATH( '/assets/script.min.js' ), array(), '1.0.0' );
        $main_script_deps[] = __MAIN_PREFIX . '-js-main';

    }


    public function get_script_depends() {
        
        $scripts = [
            __MAIN_PREFIX . '-js-main'
        ];

        $settings = $this->get_settings_for_display();
                
        return $scripts;

    }



    /**
	 * Render section output in the editor.
	 *
	 * Used to generate the live preview, using a Backbone JavaScript template.
	 *
	 * @since 2.9.0
	 * @access protected
	 */
	protected function content_template() { 
?>
		<# if ( 'boxed' === settings.content_width ) { #>
			<div class="e-con-inner">
		<#
		}
		if ( settings.background_video_link ) {
			let videoAttributes = 'autoplay muted playsinline';

			if ( ! settings.background_play_once ) {
				videoAttributes += ' loop';
			}

			view.addRenderAttribute( 'background-video-container', 'class', 'elementor-background-video-container' );

			if ( ! settings.background_play_on_mobile ) {
				view.addRenderAttribute( 'background-video-container', 'class', 'elementor-hidden-phone' );
			}
			#>
			<div {{{ view.getRenderAttributeString( 'background-video-container' ) }}}>
				<div class="elementor-background-video-embed"></div>
				<video class="elementor-background-video-hosted elementor-html5-video" {{ videoAttributes }}></video>
			</div>
		<# } #>

        <# --- YOUR CUSTOM CODE --- #>

        <div class="elementor-shape elementor-shape-top"></div>
		<div class="elementor-shape elementor-shape-bottom"></div>
		<# if ( 'boxed' === settings.content_width ) { #>
			</div>
		<# } #>
		<?php
	}


    /**
     * Before section rendering.
     *
     * Used to add stuff before the section element.
     *
     * @since 1.0.0
     * @access public
     */
	public function before_render() {
        
		$settings = $this->get_settings_for_display();
		$link = $settings['link'];

		if ( ! empty( $link['url'] ) ) {
			$this->add_link_attributes( '_wrapper', $link );
		}

		?><<?php $this->print_html_tag(); ?> <?php $this->print_render_attribute_string( '_wrapper' ); ?>>
		<?php
		if ( $this->is_boxed_container( $settings ) ) { ?>
			<div class="e-con-inner">
		<?php }

		$this->render_video_background();
        

        /* --- YOUR CUSTOM RENDER CODE --- */


        if ( $settings['shape_divider_top'] ) {
            $this->render_shape_divider( 'top' );
        }

        if ( $settings['shape_divider_bottom'] ) {
            $this->render_shape_divider( 'bottom' );
        }

	}


	/**
     * After section rendering.
     *
     * Used to add stuff after the section element.
     *
     * @since 1.0.0
     * @access public
     */
	public function after_render() {
		$settings = $this->get_settings_for_display();
		if ( $this->is_boxed_container( $settings ) ) { ?>
			</div>
		<?php } ?>
		</<?php $this->print_html_tag(); ?>>
		<?php
	}

}
```

## Quality assurance

- [x] I have tested this code to the best of my abilities
- [x] I have added unittests to verify the code works as intended
- [x] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by danielezerosi** [comment]
as in the old issue, #13618

please 

@shilo-ey 
@kobizz 

approve the changes as this customization is very important to many developers

**Comment by HadyShaltout** [comment]
@mykytamurzin
@louiswol94 
@TzviRabinovitch

Hey Guys, Did you see this PR? I waited 7 months last year to approve [Extend Sections](https://github.com/elementor/elementor/pull/13618), Now, The new Containers have the same issue and I already have my own plugin that extends the old Section background and need to switch to the new Containers.

Thank You

**Comment by HadyShaltout** [comment]
Hi @louiswol94 
Did you merge it or what? After updating to the new branch the successful checks turned back to 5 of 12, I thought after you checked it last week it would be merged immediately.

Thanks

**Review by louiswol94 — APPROVED** [review]

**Comment by louiswol94** [comment]
@HadyShaltout Merged. Thank you for the contribution 😄

**Comment by HadyShaltout** [comment]
@louiswol94 Thank You

**Pull request merged**
