### PR TITLE
Make the Main Section Customizable

### PR DESCRIPTION
**Pull request by Oxibug**
## PR Checklist

- [ x ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ x ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

Give the developers the ability to customize the main section so they can use the main section background widely, like adding Canvas backgrounds instead of Videos or classic BG and it will be great to use the section background in anyway they wish.

## Description
Extend **Element_Section** class using action [elementor/elements/elements_registered] to add a new HTML output in the section's background such as using Canvas instead of Videos background, 

## Test instructions
This PR can be tested by following these steps:

* In function [init_elements] located in Elements_Manager class, I need you to add **'$this'** word to action 'elementor/elements/elements_registered' So I'll be able to use the current class's function [register_element_type] .. like that:
**do_action( 'elementor/elements/elements_registered', $this );**

* Modify functions [**get_html_tag**] and [**print_shape_divider**] located in **Element_Section** class in [section.php] to public instead of private.

* Developer can add new controls using action '**elementor/element/section/section_advanced/after_section_end**' mentioned in the opened issue [3334](https://github.com/elementor/elementor/issues/3334#issuecomment-361611013)

* Now the developer can Extends the **Element_Section** class and override the functions [**content_template**], [**before_render**], [**after_render**]

## Quality assurance

- [ x ] I have tested this code to the best of my abilities
- [ x ] I have added unittests to verify the code works as intended
- [ x ] Docs have been added / updated (for bug fixes / features)

Fixes #

* FILE: **\elementor\includes\managers\elements.php** - Add [$this] word in the action

```
private function init_elements() {
    
    /* --> Add $this word */
    do_action( 'elementor/elements/elements_registered', $this );

}
```

* FILE: **\elementor\includes\elements\section.php** - Make the following functions **public** instead of private

```
public function get_html_tag() {
    
}

public function print_shape_divider( $side ) {
    
}

```

* Now, The developer can copy the three function [**content_template**], [**before_render**], [**after_render**] from **\elementor\includes\elements\section.php**
* Use the action [**elementor/elements/elements_registered**] after adding **$this** to point to the parent class and extend his new section **with the same implementation of the Elementor Plugin's Section** but now he can add his own HTML output as he wish

```
class ModifyElementorSection {

    public function __construct() {
        add_action( 'elementor/elements/elements_registered',         [ $this, 'modify_section' ] );
    }

    public function modify_section( $el_manager ) {        

        $el_manager->register_element_type( new Customizable_Section() );

    }

}

class Customizable_Section extends \Elementor\Element_Section {

    public function content_template() {
        /* Copy the Elementor's section form the Plugin Then append your new HTML output */
    }

    public function before_render() {
        /* Copy the Elementor's section form the Plugin Then append your new HTML output */
    }

    public function after_render() {
        /* Copy the Elementor's section form the Plugin Then append your new HTML output */
    }

}
```

### CODE REVIEW

**Comment by shilo-ey** [comment]
Please send a PR only with the affected files so we could review it.

**Comment by Oxibug** [comment]
@shilo-ey 

* FILE: **\elementor\includes\managers\elements.php** - Add [$this] word in the action

```
private function init_elements() {
    
    /* --> Add $this word */
    do_action( 'elementor/elements/elements_registered', $this );

}
```

* FILE: **\elementor\includes\elements\section.php** - Make the following functions **public** instead of private

```
public function get_html_tag() {
    
}

public function print_shape_divider( $side ) {
    
}

```

**Comment by shilo-ey** [comment]
Please send a proper PR with only the affected files.

Please create a PR from your fork of Elementor

**Comment by Oxibug** [comment]
@shilo-ey 
I fork the Elementor and made the changes, Correct?

**Comment by Oxibug** [comment]
@shilo-ey 
Hi There, It seems like you forget the request, waiting for more than a month :)
The new request: https://github.com/elementor/elementor/pull/13618

**Pull request closed without merging**
