### PR TITLE
a11y / i18n: Remove HTML arrow from translation string

### PR DESCRIPTION
**Pull request by ramiy**
**LTR:**

i18n-a11y

----

**RTL:**

a11y-i18n

### CODE REVIEW

**Comment by ramiy** [comment]
The new arrow is using [Elementor Font Icons](https://pojome.github.io/elementor-icons/) and has aria tags for better accessibility.

**Comment by ramiy** [comment]
**The new font icon:**

**Comment by arielk** [comment]
@ramiy please sent it to v2.1.0

**Comment by ramiy** [comment]
@KingYes @arielk changing the branch creates conflicts. As the PR was created using GitHub inline file editing, I can't resolve the conflicts on my computer.

**Pull request merged**
