### PR TITLE
Tweak: Added text stroke for some widgets [ED-6780]

### PR DESCRIPTION
**Pull request by rodolphebertozzo**
- Tweak: Added text stroke to number for counter widget
- Tweak: Added text stroke to title for counter widget
- Tweak: Added text stroke to text for divider widget
- Tweak: Added text stroke to title for image box widget

### CODE REVIEW

**Comment by rami-elementor** [comment]
PR name linter is failing.

`Run echo " Tweak: Added text stroke for some widgets [ED-6794]"`

It starts with a space. You need to remove the space.

**Comment by rodolphebertozzo** [comment]
@rami-elementor. Done!

**Comment by rodolphebertozzo** [comment]
@rami-elementor ?

**Comment by rami-elementor** [comment]
I'm sorry, this PR won't be merged to v3.7. It was postponed to v3.8.

**Comment by rodolphebertozzo** [comment]
Hi @rami-elementor,
No problem, I pushed version 3.8 in this one to make sure there are no conflicts since the file changes.

**Comment by rodolphebertozzo** [comment]
@KingYes

**Pull request merged**
