### PR TITLE
Tweak : Add Responsive Options To Column Text Align

### PR DESCRIPTION
**Pull request by rodolphebertozzo**
fix : https://github.com/elementor/elementor/issues/13199

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

### CODE REVIEW

**Comment by rodolphebertozzo** [comment]
@kobizz

**Comment by rodolphebertozzo** [comment]
@KingYes

**Comment by rodolphebertozzo** [comment]
@arielk

**Comment by rodolphebertozzo** [comment]
@KingYes

**Comment by ramiy** [comment]
@rodolphebertozzo

Why only columns? what about sections?

**Comment by rodolphebertozzo** [comment]
Hi @ramiy,
I have opened a new PR in which I also include the sections, because I can't merge the last branch into this one in order to apply the changes of the escaped methods of translations of Wordpress. : https://github.com/elementor/elementor/pull/16215

**Pull request closed without merging**
