### PR TITLE
feat: make position a responsive control

### LINKED ISSUE #10123: Elementor Widget-> Advanced -> Positioning -> Resonsive missed for Position
Hi Guys,

Good Day!

Screenshot_12

I want to describe something in above picture, as we can see that in "positioning" have responsive option  Screenshot_13 , but "Position" don't have any responsive option.

so i would like to suggest the developers please add this features in coming updates.

Thanks, hope you get my point.

### PR DESCRIPTION
**Pull request by m1ga**
## PR Checklist

- [x] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* make position a responsive control

## Description
An explanation of what is done in this PR

* The current position setting is not responsive so you can't switch between relative and absolute position without custom CSS.

## Test instructions
This PR can be tested by following these steps:

* add a container
* set a min height, width and background color
* switch to tablet mode
* set `position` to `absolute`

## Quality assurance

- [x] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes https://github.com/elementor/elementor/issues/10123

### CODE REVIEW

**Comment by lavendaniel** [comment]
This doesn't work.

**Comment by m1ga** [comment]
@lavendaniel as I just switched from `add_control` to `add_responsive_control` I didn't do anything special in the code. What did not work?

Here is a quick video: 

https://github.com/elementor/elementor/assets/4334997/554afbaa-7474-480c-ad7c-2a93c702cbca

**Comment by lavendaniel** [comment]
> @lavendaniel as I just switched from `add_control` to `add_responsive_control` I didn't do anything special in the code. What did not work?
> 
> Here is a quick video:
> 
>  simplescreenrecorder-2023-11-13_13.24.21_edit.mp4

Hi Michael,

Mine is super buggy. Made the exact changes as given.

For me horizontal orientation (part of absolute position control) disappears. The position type difference seems to hold between desktop and tablet but it absolutely hates any difference between tablet and mobile, just won't have it (want mobile as default and the others on right-nested absolute).

Maybe for what I need to do I could get away with trying to make the horizontal absolute position responsive.


https://github.com/elementor/elementor/assets/134405583/54773754-9758-4558-8b3b-5b25841ed370

Kind Regards

**Comment by m1ga** [comment]
Ah ok. First: you are working on a widget level. I only tested the container part. Then (as mentioned in the reddit post but I'll put it here too):

The current way only allows you to go from default to fixed/absolute. You can't switch back to "default" as that is "empty" in this case so it won't override the previous more specific one.

In order to go back to relative you have to add
```
'relative' => esc_html__( 'Relative', 'elementor' ),
```
into the list. That would require some more changes or testing. I'll wait and see if this PR is interesting for the maintainers in general or not. I don't expect it to be merged anytime soon as the original issue is very old and no action was taken there.

**Pull request closed without merging**
