### PR TITLE
Icon list element transition on hover

### PR DESCRIPTION
**Pull request by wayheming**
#7821

### CODE REVIEW

**Comment by wayheming** [comment]
Hello @bainternet could you take a look at the pull request?

**Comment by wayheming** [comment]
@bainternet Hello)

**Comment by bainternet** [comment]
@wayheming 
can you please sign our CLA?

**Comment by wayheming** [comment]
> @wayheming
> can you please sign our CLA?

Yes i signed

**Comment by rami-elementor** [comment]
Closing this PR. An updated code can be found in #21274

**Pull request closed without merging**
