### PR TITLE
Tweak: Image Carousel widget enhancements

### PR DESCRIPTION
**Pull request by rodolphebertozzo**
- Added a space between the navigation bubbles and the image area
- Added customizable image size, width and max-width
- Added units for custom space between images
- Added box shadow option
- Added padding to caption
- Added Opacity 
- Added  CSS filter
- Added object fit option to image
- Added responsive control for alignment of caption
controle
controle2
controle3
146925580-c6ccefa6-07e9-4017-9d8c-6e076223ec2a

Fixes : https://github.com/elementor/elementor/issues/12533 https://github.com/elementor/elementor/issues/11368 https://github.com/elementor/elementor/issues/11348

### CODE REVIEW

**Comment by rodolphebertozzo** [comment]
@shilo-ey @matipojo @kobizz

**Comment by rodolphebertozzo** [comment]
@arielk

**Comment by rodolphebertozzo** [comment]
@matipojo, it's ready for review

**Comment by rodolphebertozzo** [comment]
@avivu ?

**Comment by avivu** [comment]
Hello @rodolphebertozzo ,

Sorry for the delay with the review and answer.

First, thank you for all of your work. It is very appreciated.
We went over all of your suggestions for improving the image carousel, and there are a lot of good changes.

At this moment, we would like to put your changes on hold because we want to take a broad look at all of our carousel widgets and understand how to improve all of them with more content and style possibilities and better consistency.

We will take all of your changes into consideration later on.
Again, thank you!

**Comment by rodolphebertozzo** [comment]
Hi @avivu,
As you wish, in any case, you have a complete improvement of this widget that is mergeable as soon as you want in the 3.6 branch, many people let me know that they need these improvements, feel free to include them, you will not be disappointed, and tell me what to change in the code?

**Comment by avivu** [comment]
Hi @rodolphebertozzo,

We want to inspect improvements in all of our carousel widgets, so we will take our time to research and understand what to change. Thank you for your hard work, and I'm sure later on we could implement your code.

**Pull request closed without merging**
