### PR TITLE
Icon on the flyover

### LINKED ISSUE #12058: Tweak : add icon on flyover widget Button
on the "BUTTON" widget, there is the possibility to add an icon (on the right or on the left), so an option should be added so that the button icon appears only when the user passes over the button with the mouse

### PR DESCRIPTION
**Pull request by rodolphebertozzo**
On the "BUTTON" widget, there is the possibility to add an icon (on the right or on the left), so an option should be added so that the button icon appears only when the user passes over the button with the mouse

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #12058

### CODE REVIEW

**Comment by rodolphebertozzo** [comment]
@Nevoss

**Comment by rodolphebertozzo** [comment]
Hi @udidol, I finally managed to develop the functionality with CSS can you take a look at this PR?

**Review by udidol — COMMENTED** [review]
@rodolphebertozzo

A few things:
1. You cannot use the `selector` keyword in SCSS files. The `selector` keyword is a special keyword we in Elementor added to our Custom CSS module to allow our users to easily target element wrappers.
2. The CSS you created isn't valid. I suggest you Google and learn some basic CSS, specifically about the `:hover` pseudo-class and how to use it.
3. You have added a control to the Button widget, but you did not do anything to connect between that control and your CSS classes. I suggest you learn more about `selectors` and `prefix_class` control arguments. Googling finds you a lot of useful information for learning. Here is an article about selectors, for example: https://letswp.io/selectors-elementor-control-css-values/

**Comment by rodolphebertozzo** [comment]
> @rodolphebertozzo
> 
> A few things:
> 
> 1. You cannot use the `selector` keyword in SCSS files. The `selector` keyword is a special keyword we in Elementor added to our Custom CSS module to allow our users to easily target element wrappers.
> 2. The CSS you created isn't valid. I suggest you Google and learn some basic CSS, specifically about the `:hover` pseudo-class and how to use it.
> 3. You have added a control to the Button widget, but you did not do anything to connect between that control and your CSS classes. I suggest you learn more about `selectors` and `prefix_class` control arguments. Googling finds you a lot of useful information for learning. Here is an article about selectors, for example: https://letswp.io/selectors-elementor-control-css-values/

@udidol, following our last conversation, I made the necessary changes to the functionality, can you review it again on this one : https://github.com/elementor/elementor/pull/14139

**Pull request closed without merging**
