### PR TITLE
Provide a clientside devicemode-hook

### PR DESCRIPTION
**Pull request by R0Wi**
## PR Checklist

- [x] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* Added a new clientside hook 'frontend/handlers/page/device_mode', which is fired when the devicemode is determined. 

## Description
An explanation of what is done in this PR

* This allows the usage of a library (like [mobile detect](http://hgoebl.github.io/mobile-detect.js/)) for detecting wheter the client is a desktop-, tablet- or mobile-device, instead of just checking the clients viewport width. This is helpful when dealing with high-resolution devices like ipad-pro. These devices are detected as "desktop" at the moment, which can produce trouble sometimes, e.g. when dealing with different settings for "desktop" and "tablet". 

## Test instructions
This PR can be tested by following these steps:

* Register for the new js-hook like this and determine the devicemode yourself:
```javascript 
     elementorFrontend.hooks.addFilter( 'frontend/handlers/page/device_mode', function( devmode ) {
           // do some detection
            var deviceModeNew = someMagicMethod();
            return deviceModeNew;
        } );
```
## Quality assurance

- [x] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

## Todo
* Add the hook to the dev-documentation at https://code.elementor.com/js-hooks/

Fixes #

### CODE REVIEW

**Comment by R0Wi** [comment]
Is there a chance to get some feedback on this?

**Comment by bainternet** [comment]
@R0Wi 

Thanks for the PR, But we can't accept it, since our JS and CSS are depended on these values and we do not support any other values yet.

We are looking to add more BreakPoints/Viewports support in the future.

Thanks.

**Comment by MrBushid0** [comment]
Is there currently a way via JS to detect when the preview mode changes in the editor?

**Comment by R0Wi** [comment]
I didn't really understand your question. What do you want to achieve?

**Comment by MrBushid0** [comment]
> I didn't really understand your question. What do you want to achieve?

Hi, I'm trying to detect via JS when the preview frame changes to different Responsive Modes (desktop, tablet, mobile) when in edit mode.

**Comment by R0Wi** [comment]
@MrBushid0 i just know the following:
If you're in editmode inside of Elementor you will have an `iframe` where the preview is shown
```html
<iframe id="elementor-preview-iframe" src="<YOUR_DOMAIN>" allowfullscreen="1">
    <!-- [ ... ] -->
</iframe>
```
The preview in that `iframe` contains a `body` tag with an attribute called `data-elementor-device-mode`
```html
<body class="..." data-elementor-device-mode="tablet" style="overflow-x: hidden;">
```
In the debugger you can see that this attribute changes if you switch between `deskop`, `tablet` and `mobile`. So a possible solution would be to listen to this attribute changes.

Maybe that helps.

**Pull request closed without merging**
