### PR TITLE
Tweak: Make the Image Size responsive in the Testimonial widget [ED-13173]

### PR DESCRIPTION
**Pull request by rodolphebertozzo**
Closes: https://github.com/elementor/elementor/discussions/18977

### CODE REVIEW

**Comment by rodolphebertozzo** [comment]
@arielk

**Comment by rodolphebertozzo** [comment]
@rami-elementor

**Comment by rodolphebertozzo** [comment]
@rami-elementor

**Comment by rami-elementor** [comment]
@rodolphebertozzo This PR doesn't closes the issue you mentioned in the description.

**Comment by rami-elementor** [comment]
@rodolphebertozzo FYI, I've updated the branch and it looks like that 2/3 of the original controls you proposed are already responsive. The updated PR adds responsive capabilities to only one control.

**Comment by rodolphebertozzo** [comment]
> @rodolphebertozzo FYI, I've updated the branch and it looks like that 2/3 of the original controls you proposed are already responsive. The updated PR adds responsive capabilities to only one control.

Yes, but these controls became responsive after my PR was sent, another PR was opened to offer the same thing, but not all widgets were included, that's why when you synchronized my branch with the latest version, only a modified file remains.

**Review by rami-elementor — APPROVED** [review]

**Comment by rami-elementor** [comment]
Once again, thank you for your contribution. PR approved and moved to @arielk for merge.

**Review by arielk — APPROVED** [review]

**Pull request merged**
