### PR TITLE
Update Google Fonts list

### PR DESCRIPTION
**Pull request by daviedR**
Add some missing fonts on the list.

### CODE REVIEW

**Comment by KingYes** [comment]
Hi @daviedR 
Thank you for your PR. But why you remove all `earlyaccess` fonts?

**Comment by KingYes** [comment]
Thanks @daviedR 
BTW, I just restore earlyaccess fonts by this commit: c375684b78628bef9e716c60eb04302337036826

**Comment by daviedR** [comment]
Oops sorry, didn't really mean it :)

**Comment by KingYes** [comment]
It's okay :)

**Pull request merged**
