### PR TITLE
Tweak : add Tiktok Icon

### LINKED ISSUE #11763: TikTok Icon
Font Awesome now has TikTok icon in their library.. Can you please consider updating it?

Issue : #9423

TIA

### PR DESCRIPTION
**Pull request by rodolphebertozzo**
fix : #11763

### CODE REVIEW

**Review by joshmarom — APPROVED** [review]
https://fontawesome.com/icons/tiktok?style=brands
https://www.schemecolor.com/tiktok.php

Checks out

**Comment by joshmarom** [comment]
Please sign the CLA

**Comment by rodolphebertozzo** [comment]
Hi @joshmarom, thanks for your feedbacks, I put the main color of the logo at the background level, namely : #010101

**Comment by lisaschumann** [comment]
hey there! is this just awaiting merging? this would be a super helpful feature.

**Comment by rami-elementor** [comment]
Closing PR. This feature was add in Elementor 3.1.

**Pull request closed without merging**
