### PR TITLE
Update Repeater docs

### PR DESCRIPTION
**Pull request by iamntz**
1. Added `selectors` mentions
1. Added the `Repeater` class sample

### CODE REVIEW

**Comment by ramiy** [comment]
@iamntz Thank you for your PR, I've updated the docs.

https://developers.elementor.com/elementor-controls/repeater-control/

**Comment by iamntz** [comment]
Great! Please also add a mention about `CURRENT_ITEM` selector:

https://github.com/pojome/elementor/pull/4011/files#diff-2f21abce7471243e375875180bfc8a16R112

**Comment by ramiy** [comment]
@iamntz Added, thanks!

**Comment by iamntz** [comment]
Almost there! You still need to mention [`elementor-repeater-item`](https://github.com/pojome/elementor/pull/4011/files#diff-2f21abce7471243e375875180bfc8a16R121) class name (don't forget the JS) ! 😁

**Pull request closed without merging**
