### PR TITLE
New: Submissions - Promotion [ED-2153]

### PR DESCRIPTION
**Pull request by Nevoss**
ref: ED-2153

### CODE REVIEW

**Review by StyleShit — APPROVED** [review]
LGTM.

**Review by matipojo — CHANGES_REQUESTED** [review]
Please pull 3.3.0

**Review by matipojo — CHANGES_REQUESTED** [review]
Please re-pull 3.3.0 (for PR name linter)

**Comment by Nevoss** [comment]
> Please re-pull 3.3.0 (for PR name linter)

Done

**Review by matipojo — APPROVED** [review]

**Pull request merged**
