### PR TITLE
Include various fonts from Google Fonts

### LINKED ISSUE #8996: Please update Google Fonts library to all the latest fonts available.
Hey Elementor, please update Google Fonts library as I miss this one here along with others: https://fonts.google.com/selection?query=manj&selection.family=Manjari:100,400,700
Thank you!!

### PR DESCRIPTION
**Pull request by programmin1**
Fixes  #8996 - missing some fonts.

- [X] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?
- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:
One commit to fix #8996 - missing some fonts.

*

## Description
An explanation of what is done in this PR: Added a few Google fonts that were missing.

*

## Test instructions
This PR can be tested by following these steps:
Go to fonts. Find one of those added below. They work.

*

## Quality assurance

- [X] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #8996

### CODE REVIEW

**Comment by KingYes** [comment]
Hey @programmin1 

Please sign on our CLA..

**Comment by programmin1** [comment]
System kept timing out, but I did get to this... gpl is fine... problem is it doesn't think the username on this particular computer commited with is valid. I added email so it should be good?

**Comment by programmin1** [comment]
The one commit is https://github.com/elementor/elementor/pull/9241/commits/54293af2800fde1b4f740ebf586ebcd18fc487c9 if you want to cherry-pick.

**Comment by matipojo** [comment]
OK, thanks.

**Pull request closed without merging**
