### PR TITLE
Optimize string

### PR DESCRIPTION
**Pull request by pedro-mendonca**
Make it a complete string, using the same coding pattern of core https://core.trac.wordpress.org/browser/trunk/src/wp-admin/includes/update.php#L527

### CODE REVIEW

**Comment by pedro-mendonca** [comment]
About this message title, what is the meaning of "#NewInElementor" ?
It's not clear. How should this be translated?

**Comment by KingYes** [comment]
It's still under development :)

**Comment by pedro-mendonca** [comment]
@KingYes thanks, I'll for it's substitute :)
Still, the message I've changed in this PR is fully working.

**Comment by pedro-mendonca** [comment]
Hi,
The problem with https://github.com/pojome/elementor/commit/7c78d49df150023174e27704736c931eb38e58a0 is that " or " is out of gettex function. It would be better to keep it as a complete sentence.

**Comment by pedro-mendonca** [comment]
Closing this to solve conficts

**Pull request closed without merging**
