### PR TITLE
Tweak: Responsive text-align in Columns & Sections [ED-6803]

### PR DESCRIPTION
**Pull request by rodolphebertozzo**
I tested and the predefined parameters are saved when you switch to another breakpoint
align
align2
align3
fix: https://github.com/elementor/elementor/issues/13199

### CODE REVIEW

**Comment by rodolphebertozzo** [comment]
@KingYes

**Comment by rodolphebertozzo** [comment]
@matipojo

**Comment by rodolphebertozzo** [comment]
@arielk

**Comment by rodolphebertozzo** [comment]
@ramiy

**Comment by rami-elementor** [comment]
@rodolphebertozzo Can you change to 3.7.0 release?

**Comment by rodolphebertozzo** [comment]
@rami-elementor, done!

**Comment by rami-elementor** [comment]
I'm sorry, this PR won't be merged to v3.7. It was postponed to v3.8.

**Pull request merged**
