### PR TITLE
Fix: Multiple repeaters in same widget has conflicts [ED-4001]

### LINKED ISSUE #13117: The Form widget does not work if the widget has a custom repeater in the Advanced tab
When create the custom repeater (Ex: https://prnt.sc/vm8iy0) for all the widgets following the instructions ( https://developers.elementor.com/how-to-add-a-repeater-control-to-elementor-add-on/ ), I’ve faced the problem that in the Forms widget the fields from my repeater also get in the repeater form fields of the Form widget https://prnt.sc/vm8jlh. It causes the crushing of the form.

I’ve already tested this issue with other addons for Elementor. They add their repeaters for the widgets and the same situation occurs.

My code for adding repeater:
```
add_action( 'elementor/element/common/_section_style/after_section_end', function( $element, $args ) {

	$element->start_controls_section(
		'_my_custom_section',
		[
			'label' => 'Custom Section',
			'tab'   => Elementor\Controls_Manager::TAB_ADVANCED,
		]
	);

	$repeater = new Elementor\Repeater();

	$repeater->add_control(
		'_custom_text_1',
		[
			'label'   => 'Text1',
			'type'    => Elementor\Controls_Manager::TEXT,
			'default' => '',
		]
	);

	$repeater->add_control(
		'_custom_text_2',
		[
			'label'   => 'Text2',
			'type'    => Elementor\Controls_Manager::TEXT,
			'default' => '',
		]
	);

	$element->add_control(
		'_my_custom_repeater',
		[
			'label'  => 'Custom Repeater',
			'type'   => Elementor\Controls_Manager::REPEATER,
			'fields' => $repeater->get_controls(),
			'title_field' => '{{{ _custom_text_1 }}}',
		]
	);

	$element->end_controls_section();

}, 10, 2 );
```

### PR DESCRIPTION
**Pull request by Nevoss**

### CODE REVIEW

**Review by joshmarom — APPROVED** [review]

**Review by matipojo — CHANGES_REQUESTED** [review]
Please pull from develop

**Review by matipojo — APPROVED** [review]

**Comment by bradallenfisher** [comment]
is this going to make a backport to 3.4?

**Comment by Aviad-Herman** [comment]
Hey @bradallenfisher,
No, it's going to take affect on Elementor 3.5.0 and up
BTW, what is the advantage of backporting as an alternative to updating Elementor?

**Comment by bradallenfisher** [comment]
@Aviad-Herman so we don't have to keep hacking 3.4 until 3.5 comes out. If you aren't going to merge these into the 3.4 branch we will have to wait until there is a 3.5 release.

**Comment by Aviad-Herman** [comment]
Yes good point.
BTW, the reason we are waiting for 3.5.0 is because we ant this fix to undergo a beta phase before being released to the general public. In the meantime, you can pull the fix and install for yourself. Do you want me to create a zip file for you?

**Comment by bradallenfisher** [comment]
@Aviad-Herman I appreciate that but i only need this for a production site at the moment. Hence my hesitation to run beta or dev. Thanks!

**Pull request merged**
