### PR TITLE
Solution of Undefined index: pro_widgets

### PR DESCRIPTION
**Pull request by codersaiful**
I got a issue on api.php line 160.
Undefined index: pro_widgets in %location%/wp-content/plugins/elementor\includes\api.php on line 160

## PR Checklist

- [x] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [x] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

### CODE REVIEW

**Comment by codersaiful** [comment]
Issue: https://github.com/elementor/elementor/issues/15542

**Comment by mak-alamin** [comment]
Same issue having here and this solution solved it. Thank you.

**Comment by shilo-ey** [comment]
Thank you for your contribution. this was merged by another PR.

**Comment by codersaiful** [comment]
thanks a lot

**Pull request closed without merging**
