### PR TITLE
Tweak: Background video should have a background color [ED-8437]

### PR DESCRIPTION
**Pull request by ramiy**
Sections and columns have have Classic background (color / image), Gradient, Video or Slideshow.

The video background is missing a fallback background color displayed while the video is loaded.

This PR added a background color control to the video bg.

Before:

video-bg-before

After:
video-bg-after

## PR Checklist

- [x] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* Background video should have a background color as fallback while the video is loading

## Description
An explanation of what is done in this PR

* Background video should have a background color as fallback while the video is loading

## Test instructions
This PR can be tested by following these steps:

* Edit any **Section**
* Click the **Style** tab
* In the **Background** area
* Set the **Background Type** to **Video**
* Choose the **Color** - it will be used ab fallback color while the video is loading.

## Quality assurance

- [x] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

### CODE REVIEW

**Comment by ramiy** [comment]
@matipojo

**Comment by rodolphebertozzo** [comment]
+1

**Comment by rodolphebertozzo** [comment]
@shilo-ey, I find this feature interesting as well, can you take a look at it?

**Review by udidol — APPROVED** [review]

**Review by arielk — APPROVED** [review]

**Comment by arielk** [comment]
Fix: https://github.com/elementor/elementor/issues/4353

**Pull request merged**
